/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PTTVerifier } from "./PTTVerifier";
export type { PrimeToadIDVerifier } from "./PrimeToadIDVerifier";
