/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICircuitValidator } from "./ICircuitValidator";
export type { IZKPVerifier } from "./IZKPVerifier";
